// Generates the npm package's contents from this repository's sources:
//
//   abi/<Contract>.json   the ABIs, from the Foundry build of contracts/
//   index.js, index.d.ts  the same ABIs plus the deployed addresses, from
//                         contracts/deployments/deployments.ts and verifier-codehashes.json
//
//   node scripts/build-abi.mjs           regenerate (runs `forge build` in contracts/)
//   node scripts/build-abi.mjs --check   fail if the committed files differ from what the sources give
//
// Needs Foundry, contracts/node_modules (`npm ci` in contracts/) and Node.js >= 22.18, which imports
// deployments.ts directly. The output is a pure function of the sources: same input, same bytes.
import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const CONTRACTS = join(ROOT, 'contracts');

/** Export name -> the Foundry artifact it comes from. */
const ABIS = {
  darkVaultAbi: 'DarkVault',
  darkKeyRegistryAbi: 'DarkKeyRegistry',
  darkVerifierAbi: 'IDarkVerifier',
  timelockAbi: 'TimelockController',
};

execFileSync('forge', ['build', '--quiet'], { cwd: CONTRACTS, stdio: ['ignore', 'ignore', 'inherit'] });
const abis = Object.fromEntries(Object.entries(ABIS).map(([name, contract]) => {
  const artifact = JSON.parse(readFileSync(join(CONTRACTS, 'out', `${contract}.sol`, `${contract}.json`), 'utf8'));
  return [name, artifact.abi];
}));

const { deployments } = await import(pathToFileURL(join(CONTRACTS, 'deployments', 'deployments.ts')).href);
const pins = JSON.parse(readFileSync(join(CONTRACTS, 'deployments', 'verifier-codehashes.json'), 'utf8'));

const same = (a, b) => typeof a === 'string' && typeof b === 'string' && a.toLowerCase() === b.toLowerCase();
const chains = {};
for (const [chainId, pin] of Object.entries(pins)) {
  if (chainId === '_') continue;
  const d = deployments[chainId];
  if (!d) throw new Error(`chain ${chainId} is pinned but has no entry in deployments.ts`);
  // The two records are written separately; refuse to publish addresses they disagree on.
  const pinned = {
    DarkVault: d.vault,
    DarkKeyRegistry: d.registry,
    DarkRegisterVerifier: d.verifiers.register,
    DarkTransferVerifier: d.verifiers.transfer,
    DarkWithdrawVerifier: d.verifiers.withdraw,
  };
  for (const [contract, address] of Object.entries(pinned)) {
    if (!same(pin[contract]?.address, address)) {
      throw new Error(`chain ${chainId}: deployments.ts has ${contract} at ${address}, the pins file at ${pin[contract]?.address}`);
    }
  }
  // Every address published must be a real one: a missing field would otherwise vanish from the JSON.
  const a = (address, what) => {
    if (!/^0x[0-9a-fA-F]{40}$/.test(address ?? '') || /^0x0{40}$/.test(address)) {
      throw new Error(`chain ${chainId}: ${what} is ${address}`);
    }
    return address;
  };
  const v = d.verifiers;
  chains[chainId] = {
    chainId: Number(chainId),
    deployBlock: Number(d.deployBlock),
    vault: a(d.vault, 'vault'),
    registry: a(d.registry, 'registry'),
    verifiers: { register: a(v.register, 'register verifier'), transfer: a(v.transfer, 'transfer verifier'), withdraw: a(v.withdraw, 'withdraw verifier') },
    libraries: { RelationsLib: a(pin.RelationsLib?.address, 'RelationsLib'), ZKTranscriptLib: a(pin.ZKTranscriptLib?.address, 'ZKTranscriptLib') },
    timelock: a(d.timelock, 'timelock'),
    guardian: a(d.guardian, 'guardian'),
    usdg: a(d.usdg, 'usdg'),
    codehashes: Object.fromEntries(Object.keys(pin).sort().map((contract) => [contract, pin[contract].codehash])),
    rpcUrl: d.rpcUrl,
    explorer: d.explorer,
  };
}

const json = (value) => JSON.stringify(value, null, 2);
const HEADER = '// Generated by scripts/build-abi.mjs from contracts/. Do not edit.\n';
const exportsOf = (declare) =>
  HEADER +
  Object.entries(abis).map(([name, abi]) => `\nexport ${declare(name, json(abi))}\n`).join('') +
  `\nexport ${declare('deployments', json(chains))}\n`;

const files = {
  ...Object.fromEntries(Object.entries(ABIS).map(([name, contract]) => [`abi/${contract}.json`, `${json(abis[name])}\n`])),
  'index.js': exportsOf((name, value) => `const ${name} = ${value};`),
  // The literal types keep every function, event and error name, so viem and abitype infer
  // argument and return types from these ABIs.
  'index.d.ts': exportsOf((name, value) => `declare const ${name}: ${value};`),
};

if (process.argv.includes('--check')) {
  const stale = Object.entries(files).filter(([path, content]) => {
    const file = join(ROOT, path);
    return !existsSync(file) || readFileSync(file, 'utf8') !== content;
  });
  for (const [path] of stale) console.error(`  stale: ${path}`);
  if (stale.length) {
    console.error('[build-abi] committed output differs from the sources: run node scripts/build-abi.mjs');
    process.exit(1);
  }
  console.log(`[build-abi] ${Object.keys(files).length} generated files match the sources`);
} else {
  mkdirSync(join(ROOT, 'abi'), { recursive: true });
  for (const [path, content] of Object.entries(files)) writeFileSync(join(ROOT, path), content);
  console.log(`[build-abi] wrote ${Object.keys(files).join(', ')}`);
}
