// Extract the SRS slice the browser prover needs, once, so it never has to be fetched at runtime.
//
//   node circuits/tools/extract-srs.mjs
//
// Why this exists: bb.js, left alone, downloads the structured reference string from Aztec's CDN
// the first time it proves. That tells a third party the user's IP address at the exact moment they
// are making a private payment — the precise metadata this product exists to avoid. So the slice is
// extracted here, pinned by hash, and handed to bb.js with `skipSrsInit`.
//
// Output: circuits/srs/{g1.dat, g2.dat, MANIFEST.json}. The G1 slice is 2^17 points (bb's 4 MiB
// chunk; the circuits' gate counts are all under 2^16, see manifest.json), stored uncompressed when
// no compressed cache exists (8 MiB).
import { createHash } from 'node:crypto';
import { mkdirSync, writeFileSync, readFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const CIRCUITS = join(HERE, '..');
const OUT = join(CIRCUITS, 'srs');

// The spec assumed a 2^16 + 1 point slice, one per gate plus one. bb refuses that: it wants
// the compressed buffer in whole 4 MiB chunks —
//   "SrsInitSrs: compressed points_buf size 2097184 must be a positive multiple of 4194304"
// — so the smallest thing it will accept is 2^17 points, 4 MiB. That is what ships. Still bundled
// and still pinned; simply bigger than the spec expected, and lazily loaded with bb.js itself.
const POINT_BYTES = 32; // compressed
const CHUNK_BYTES = 4 * 1024 * 1024; // bb's granularity
const NUM_POINTS = CHUNK_BYTES / POINT_BYTES; // 131,072 = 2^17
const LOG_SIZE = 16; // the gate budget the circuits are held to

const manifest = JSON.parse(readFileSync(join(CIRCUITS, 'manifest.json'), 'utf8'));
const biggest = Math.max(...Object.values(manifest.circuits).map((c) => c.gate_count));
if (biggest > 2 ** LOG_SIZE) {
  console.error(`[extract-srs] a circuit needs ${biggest} gates, over the 2^${LOG_SIZE} slice. Raise LOG_SIZE.`);
  process.exit(1);
}
console.log(`[extract-srs] largest circuit is ${biggest} gates, within 2^${LOG_SIZE}`);

// bb hash-checks each 4 MiB compressed chunk, so the COMPRESSED form is what must ship. bb.js's
// Crs hands back whatever its cache holds, which is usually the decompressed 64 B/point copy, so
// prefer bb's own compressed cache file and fall back to the library.
const CACHE = join(process.env.HOME ?? '', '.bb-crs', 'bn254_g1_compressed.dat');
const { Crs } = await import('@aztec/bb.js');
const crs = await Crs.new(NUM_POINTS);
const g2 = Buffer.from(crs.getG2Data());

let g1;
let form;
const cached = existsSync(CACHE) ? readFileSync(CACHE) : null;
if (cached && cached.length >= CHUNK_BYTES) {
  // bb hash-checks each 4 MiB compressed chunk, so this is the smallest thing that ships.
  g1 = cached.subarray(0, CHUNK_BYTES);
  form = 'compressed';
} else {
  // No full compressed chunk available. The uncompressed form (64 B/point) is auto-detected by bb
  // and carries no chunk-hash check, so it works — it is simply twice the bytes.
  const raw = Buffer.from(crs.getG1Data());
  const perPoint = raw.length / crs.numPoints;
  if (perPoint !== 64) {
    console.error(`[extract-srs] unexpected G1 encoding: ${perPoint} B/point`);
    process.exit(1);
  }
  g1 = raw;
  form = 'uncompressed';
}
console.log(`[extract-srs] ${form}: ${g1.length} B for ${NUM_POINTS} points`);

// Self-test before writing: hand the bytes to bb exactly as the prover will. bb verifies each
// chunk's SHA-256 internally, so a wrong or truncated extraction fails HERE rather than shipping and
// failing in someone's browser.
const { Barretenberg } = await import('@aztec/bb.js');
const api = await Barretenberg.new({ threads: 1, skipSrsInit: true });
try {
  await api.srsInitSrs({ pointsBuf: new Uint8Array(g1), numPoints: NUM_POINTS, g2Point: new Uint8Array(g2) });
  console.log('[extract-srs] bb accepted the slice');
} catch (e) {
  console.error(`[extract-srs] bb REJECTED the slice: ${e?.message ?? e}`);
  process.exit(1);
} finally {
  await api.destroy();
}
const slice = g1;

// If a manifest is already committed, the regenerated bytes must match it. Otherwise re-running
// this tool on a different machine could silently swap the reference string the whole system's
// soundness rests on.
const pinFile = join(OUT, 'MANIFEST.json');
if (existsSync(pinFile)) {
  const prev = JSON.parse(readFileSync(pinFile, 'utf8'));
  const g1Now = createHash('sha256').update(slice).digest('hex');
  const g2Now = createHash('sha256').update(g2).digest('hex');
  if (prev.g1Sha256 !== g1Now || prev.g2Sha256 !== g2Now) {
    console.error('[extract-srs] the regenerated SRS does not match the committed manifest.');
    console.error(`  g1 ${g1Now}\n     expected ${prev.g1Sha256}`);
    console.error(`  g2 ${g2Now}\n     expected ${prev.g2Sha256}`);
    console.error('  refusing to overwrite: this is the reference string the soundness of every proof rests on.');
    process.exit(1);
  }
  console.log('[extract-srs] regenerated bytes match the committed manifest');
}

mkdirSync(OUT, { recursive: true });
writeFileSync(join(OUT, 'g1.dat'), slice);
writeFileSync(join(OUT, 'g2.dat'), g2);

const sha = (b) => createHash('sha256').update(b).digest('hex');
const pin = {
  note: 'SRS slice for the browser prover. Pinned so bb.js never fetches it at runtime, which would leak the user IP to a third party mid-payment.',
  logSize: LOG_SIZE,
  numPoints: NUM_POINTS,
  pointBytes: POINT_BYTES,
  form,
  g1Bytes: slice.length,
  g1Sha256: sha(slice),
  g2Bytes: g2.length,
  g2Sha256: sha(g2),
};
writeFileSync(join(OUT, 'MANIFEST.json'), `${JSON.stringify(pin, null, 2)}\n`);

console.log(`[extract-srs] g1 ${slice.length} B  sha256 ${pin.g1Sha256.slice(0, 16)}…`);
console.log(`[extract-srs] g2 ${g2.length} B  sha256 ${pin.g2Sha256.slice(0, 16)}…`);
console.log(`[extract-srs] wrote ${OUT}`);
