// Turns the real proofs in target/<crate>/ into circuits/evm/test/Fixtures.sol, so the Foundry
// harness verifies the same bytes bb verified. Run after tools/build.mjs.
//
// It also copies each generated verifier into evm/src/ with every top-level declaration
// suffixed. bb gives all three circuits' verifiers the same contract and library names
// (HonkVerifier + RelationsLib + ZKTranscriptLib, §19 X4), which collide when they share one
// project. verifiers/ stays byte-identical to bb's output; evm/src/ is a throwaway rename so the
// three can be measured side by side.
//
// NOT the deploy recipe. The verifiers live on 46630 were compiled from
// evm/src/<crate>.sol copies with ONLY the contract line renamed — not the every-declaration rename
// this tool performs — and that content is inside the metadata hash, so what this writes does not
// reproduce the chain. scripts/check-verifier-bytecode.mjs regenerates the deploy-time source
// itself and proves the pinned codehashes from it; treat that script as the recipe, and this as the
// fixture generator it says it is.
import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

// fileURLToPath, not .pathname: a checkout under a directory with a space gets back "%20", which
// readFileSync then takes literally (2026-09-20).
const ROOT = fileURLToPath(new URL('..', import.meta.url)).replace(/\/$/, '');
const CRATES = ['register', 'transfer', 'withdraw'];

rmSync(`${ROOT}/evm/src`, { recursive: true, force: true });
mkdirSync(`${ROOT}/evm/src`, { recursive: true });
for (const crate of CRATES) {
  let src = readFileSync(`${ROOT}/verifiers/${crate}/Verifier.sol`, 'utf8');
  const names = [...src.matchAll(/^(?:abstract contract|contract|library|interface) (\w+)/gm)].map((m) => m[1]);
  for (const n of new Set(names)) src = src.replaceAll(new RegExp(`\\b${n}\\b`, 'g'), `${n}_${crate}`);
  writeFileSync(`${ROOT}/evm/src/${crate}.sol`, src);
}

const libs = CRATES.map((crate) => {
  const proof = readFileSync(`${ROOT}/target/${crate}/proof`).toString('hex');
  const pi = readFileSync(`${ROOT}/target/${crate}/public_inputs`);
  const words = [];
  for (let i = 0; i < pi.length; i += 32) words.push(pi.subarray(i, i + 32).toString('hex'));
  const name = crate[0].toUpperCase() + crate.slice(1);
  return `library ${name}Fixture {
    bytes internal constant PROOF = hex"${proof}";

    function publicInputs() internal pure returns (bytes32[] memory pi) {
        pi = new bytes32[](${words.length});
${words.map((w, i) => `        pi[${i}] = bytes32(0x${w});`).join('\n')}
    }
}`;
}).join('\n\n');

writeFileSync(
  `${ROOT}/evm/test/Fixtures.sol`,
  `// SPDX-License-Identifier: Apache-2.0
pragma solidity >=0.8.21;

// Generated by circuits/tools/gen_fixtures.mjs from circuits/target/<crate>/{proof,public_inputs}.
// Do not hand-edit; rerun tools/build.mjs then tools/gen_fixtures.mjs.

${libs}
`,
);
console.log('wrote evm/test/Fixtures.sol');
